# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: nexu
      POSTGRES_PASSWORD: nexu-secret-password
      POSTGRES_DB: nexu-store
    volumes:
      - ./src/config/database/schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

  app:
    build: ./
    environment:
      PGUSER: nexu
      PGPASSWORD: nexu-secret-password
      PGDATABASE: nexu-store
      PGHOST: postgres
      PGPORT: 5432
    ports:
      - "3000:3000"
    depends_on:
      - postgres
